### ISSUE TITLE
Du vil få en NPE, hvis word ikke findes forvejen. Derfor skal der bruge findOrMakeWord kald. Revert din rettelse i denne statement og bare fjern opdatering af editor i findOrMakeWord

### ISSUE THREAD

**Issue by Thanerik** [Wign/Wign-design-v2#33]
Du vil få en NPE, hvis word ikke findes forvejen. Derfor skal der bruge findOrMakeWord kald. Revert din rettelse i denne statement og bare fjern opdatering af editor i findOrMakeWord

_Originally posted by @Kennik89 in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MzM2Mzg2NjM1/pull_request_reviews/more_threads_

Dette skal ikke modtage en wordId, men modtage en literal. @Kennik89 skal sørge for at alt fra Endpoint og frem i backend modtager literal og ikke wordId. Jeg sørger for at frontend sender literal med i request og ikke wordId. Deal?

**Comment by Kennik89** [comment]
Deal!

**Comment by Kennik89** [comment]
PR #46

**Comment by Thanerik** [comment]
Det skal ikke lukkes, før PR er gennemført. Du kan der referencere til denne her, og siger at PR'en vil fikse denne issue...
