### ISSUE TITLE
Lav en variabel, $userId.

### ISSUE THREAD

**Issue by Thanerik** [Wign/Wign-design-v2#36]
Lav en variabel, $userId.

Hentningen af Auth skal helst ske gennem userService, medmindre vi er 100% sikker på at det vil aldrig ændres senere, hvor getUser kan droppes.

_Originally posted by @Kennik89 in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MzM2Mzg2NjM1/pull_request_reviews/more_threads_

**Comment by Kennik89** [comment]
Igang i #48
