### ISSUE TITLE
Backend af instans søgning af ord

### ISSUE THREAD

**Issue by Kennik89** [Wign/Wign-design-v2#40]
Forberedelse af instans søgning af ord.

Læs mere i https://laravel.com/docs/master/scout#searching

**Comment by Kennik89** [comment]
elastic search server på amazon

**Comment by Thanerik** [comment]
https://madewithlove.be/how-to-integrate-elasticsearch-in-your-laravel-app-2019-edition

**Comment by Thanerik** [comment]
https://laravel.com/docs/master/scout
https://www.algolia.com/

**Comment by Thanerik** [comment]
Hvis Elastic Search, så brug Laradock:
# Use ElasticSearch
1. Run the ElasticSearch Container (elasticsearch) with the docker-compose up command: `docker-compose up -d elasticsearch`
2. Open your browser and visit the localhost on port 9200: http://localhost:9200. The default username is elastic and the default password is changeme.

## Install ElasticSearch Plugin
1. Install an ElasticSearch plugin. `docker-compose exec elasticsearch /usr/share/elasticsearch/bin/plugin install {plugin-name}`
2. Restart elasticsearch container `docker-compose restart elasticsearch`
