### ISSUE TITLE
Forbedre Form Request i Wign

### ISSUE THREAD

**Issue by Thanerik** [Wign/Wign-design-v2#52]
Den smarte ved Form Request objecter er at de allerede er "clean". Så hvis man kan udfylde Request'en på en god måde allerede fra EndPoints (At man også tilføjer creator og editor og de andre variabler ind, og validere dem) - kan koden kalde `Model::make($request)`, og vupti, så er hele modellen oprettet uden at man behøver at gøre rede på de forskellige variabler. Det er i hvert fald en idé til en forbedring her... Læs mere på https://medium.com/damilola-jolayemi/making-the-most-of-laravel-form-requests-8f07767859fc

_Originally posted by @Thanerik in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjI1MTA0ODAxOnYy/pull_request_review_threads/discussion_ som er blevet nedstemt. Denne issue er en forbedringsforslag til en senere version af Wign

**Comment by Kennik89** [comment]
Det er ikke mulig at konvertere fra issue til note i projekt, hvorfor jeg har kopieret hele indholdet over nyoprettet note. Så den vil ikke tælle med i barometeren over hvor langt er vi nået i issuerne.
Jeg lukker derved denne issue.
